#!/usr/bin/env bash
# display information about subdomains.
# Usage: 
# <domain>
# <domain> <subdomain> or <domain>

lookup_subdomain() {
    local domain=$1
    local subdomain=$2
    output=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n1)
    record_type=$(echo "$output" | awk '{print $4}')
    ip_address=$(echo "$output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $ip_address"
}

if [ "$#" -eq 2 ]; then
    lookup_subdomain "$1" "$2"
elif [ "$#" -eq 1 ]; then
    domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        lookup_subdomain "$domain" "$subdomain"
    done
else
    echo "Usage: $0 <domain> <subdomain>"
fi
