#!/usr/bin/env bash
# Installs nginx on a remote server.

sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP' # enabling traffic on port80
sudo echo "Hello World!" >> /var/www/html/hello_world
sudo service nginx start
