#!/usr/bin/env bash
# custom 404 page.

sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP' # enabling traffic on port80
#sudo chmod 777 /var/www/html -R

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default

sudo service nginx start
