#!/usr/bin/env bash
# Installs nginx on a remote server, configures a permanent redirect.

sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP' # enabling traffic on port80

# sudo chmod 755 /var/www/html -R
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i '' '/^}$/i\
        if ($request_filename ~ redirect_me){\
                rewrite ^ https://www.youtube.com/watch?v=dQw4w9WgXcQ? permanent;\
        }
' /etc/nginx/sites-available/default

sudo sed -i '' '/^}$/i\
        error_page 404 /custom_404.html;\
        location = /custom_404.html {\
                internal;\
        }
' /etc/nginx/sites-available/default

sudo service nginx start

