#!/usr/bin/env bash
# configuring web-02 to be identical to web-01 as in the previous project.
# adding a custom Nginx response header that is the hostname of the server Nginx is running on

sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP' # enabling traffic on port80

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i '/^}$/i \ location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default

sudo sed -i '' '/^}$/i\
        error_page 404 /custom_404.html;\
        location = /custom_404.html {\
                internal;\
        }
' /etc/nginx/sites-available/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo service nginx start
