#!/usr/bin/env bash
# prints the FizzBuzz thing

i=1
for i in {1..100}
do
	if [ $(( i % 3)) -eq 0 ]; then
		echo -n "Fizz"
	fi
	
	if [ $(( i % 5 )) -eq 0 ]; then
		echo -n "Buzz"
	fi

	if [ $(( i % 3 )) -ne 0 ]  && [ $(( i % 5 )) -ne 0 ]; then
		echo -n "$i"
	fi
	echo
done
