#!/usr/bin/env bash
# displaying the visitor IP and the HTTP status code from Apache log file.

awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{print $1, $2, $3}' | sort -k1,1nr -k3,3nr
