#!/usr/bin/env bash
# Printing "Best School" 10 times using the while loop.
# On the 9th iteration it prints "Hi"

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ];then
		echo "Hi"
	fi
	(( i++ ))
done
