#!/usr/bin/env bash
# Prints the hours from 0 to 12, printing the minutes from 1 till 59 in between.

h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	m=1
	while [ $m -le 59 ]
	do
		echo "$m"
		(( m++ ))
	done
	(( h++ ))
done
