#!/usr/bin/env bash
# configures an Ubuntu server where localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i "s/^127.0.0.2.*/127.0.0.2\localhost/" ~/hosts.new
sed -i "s/^8.8.8.8.*/8.8.8.8\facebook.com/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
