#!/usr/bin/env bash
#starting apache2 of a docker container from the local machine terminal

systemctl status apache2

# Getting the container ID based on the image name
image_name="holbertonschool/265-0"
container_id_or_name=$(docker ps --filter "ancestor=$image_name" --format "{{.ID}}")

# Starting Apache service inside the container
docker exec "$container_id_or_name" service apache2 start
